language: node_js
node_js:
  - "11"

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  fqdn: www.barkmin.eu
  on:
    branch: master-source

before_script:
  - yarn install

script:
  - yarn build
